"""add project fields

Revision ID: 14a093ee0542
Revises: f845e98018a5
Create Date: 2026-06-23 14:56:10.838555

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "14a093ee0542"
down_revision: Union[str, Sequence[str], None] = "f845e98018a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("novel_projects", sa.Column("target_reader", sa.String(length=200), nullable=False))
    op.add_column("novel_projects", sa.Column("language", sa.String(length=20), nullable=False))
    op.add_column("novel_projects", sa.Column("current_volume", sa.Integer(), nullable=False))
    op.add_column("novel_projects", sa.Column("current_chapter", sa.Integer(), nullable=False))
    op.add_column("novel_projects", sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("novel_projects", "archived_at")
    op.drop_column("novel_projects", "current_chapter")
    op.drop_column("novel_projects", "current_volume")
    op.drop_column("novel_projects", "language")
    op.drop_column("novel_projects", "target_reader")
    # ### end Alembic commands ###
