"""add volume_outlines table

Revision ID: 1ca20d97d89c
Revises: 7c900708c6a3
Create Date: 2026-06-23 19:01:54.167447

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "1ca20d97d89c"
down_revision: Union[str, Sequence[str], None] = "7c900708c6a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
