"""add bible tables

Revision ID: 281d66300adb
Revises: 7e879605f5e8
Create Date: 2026-06-23 17:17:22.049184

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "281d66300adb"
down_revision: Union[str, Sequence[str], None] = "7e879605f5e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
