"""add bible_candidates table

Revision ID: 3430fd95bb99
Revises: a6c232137e28
Create Date: 2026-06-23 18:03:25.683195

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "3430fd95bb99"
down_revision: Union[str, Sequence[str], None] = "a6c232137e28"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
