"""add story_genes table

Revision ID: 7652246f746e
Revises: 8914be71377d
Create Date: 2026-06-23 16:14:53.834652

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7652246f746e"
down_revision: Union[str, Sequence[str], None] = "8914be71377d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "chapters",
        "parse_source",
        existing_type=sa.VARCHAR(length=20),
        nullable=False,
        existing_server_default=sa.text("'auto'::character varying"),
    )
    op.alter_column(
        "source_documents",
        "mime_type",
        existing_type=sa.VARCHAR(length=100),
        nullable=False,
        existing_server_default=sa.text("'text/plain'::character varying"),
    )
    op.alter_column(
        "source_documents",
        "parse_status",
        existing_type=sa.VARCHAR(length=20),
        nullable=False,
        existing_server_default=sa.text("'pending'::character varying"),
    )
    op.alter_column(
        "source_documents",
        "error_message",
        existing_type=sa.TEXT(),
        nullable=False,
        existing_server_default=sa.text("''::text"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "source_documents",
        "error_message",
        existing_type=sa.TEXT(),
        nullable=True,
        existing_server_default=sa.text("''::text"),
    )
    op.alter_column(
        "source_documents",
        "parse_status",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
        existing_server_default=sa.text("'pending'::character varying"),
    )
    op.alter_column(
        "source_documents",
        "mime_type",
        existing_type=sa.VARCHAR(length=100),
        nullable=True,
        existing_server_default=sa.text("'text/plain'::character varying"),
    )
    op.alter_column(
        "chapters",
        "parse_source",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
        existing_server_default=sa.text("'auto'::character varying"),
    )
    # ### end Alembic commands ###
