"""add novel_synopses table

Revision ID: 7c900708c6a3
Revises: 3430fd95bb99
Create Date: 2026-06-23 18:27:21.310077

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "7c900708c6a3"
down_revision: Union[str, Sequence[str], None] = "3430fd95bb99"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
