"""add analysis_tasks tables

Revision ID: 7e879605f5e8
Revises: abd8b84545a2
Create Date: 2026-06-23 16:54:07.810251

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "7e879605f5e8"
down_revision: Union[str, Sequence[str], None] = "abd8b84545a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
