"""add chapter_plans table

Revision ID: 8c4450189cdb
Revises: b8d48886e250
Create Date: 2026-06-23 21:09:01.184033

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "8c4450189cdb"
down_revision: Union[str, Sequence[str], None] = "b8d48886e250"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
