"""add creative tables

Revision ID: a6c232137e28
Revises: 281d66300adb
Create Date: 2026-06-23 17:33:28.930231

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "a6c232137e28"
down_revision: Union[str, Sequence[str], None] = "281d66300adb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
