"""add chapter_analyses table

Revision ID: abd8b84545a2
Revises: 7652246f746e
Create Date: 2026-06-23 16:27:40.913103

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "abd8b84545a2"
down_revision: Union[str, Sequence[str], None] = "7652246f746e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
