"""add chapter_rhythm_plans table

Revision ID: b8d48886e250
Revises: 1ca20d97d89c
Create Date: 2026-06-23 20:35:33.993054

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "b8d48886e250"
down_revision: Union[str, Sequence[str], None] = "1ca20d97d89c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
