"""add chapter_drafts table

Revision ID: d1515cab3f4f
Revises: 8c4450189cdb
Create Date: 2026-06-23 22:00:03.716366

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d1515cab3f4f"
down_revision: Union[str, Sequence[str], None] = "8c4450189cdb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chapter_drafts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("plan_id", sa.String(length=36), nullable=False),
        sa.Column("draft_type", sa.String(length=20), nullable=False),
        sa.Column("target_words", sa.Integer(), nullable=False),
        sa.Column("person", sa.String(length=20), nullable=False),
        sa.Column("pov", sa.String(length=30), nullable=False),
        sa.Column("dialogue_density", sa.String(length=20), nullable=False),
        sa.Column("description_density", sa.String(length=20), nullable=False),
        sa.Column("pacing", sa.String(length=20), nullable=False),
        sa.Column("emotion_intensity", sa.String(length=20), nullable=False),
        sa.Column("paragraph_length", sa.String(length=20), nullable=False),
        sa.Column("language_strictness", sa.String(length=20), nullable=False),
        sa.Column("hook_strength", sa.String(length=20), nullable=False),
        sa.Column("body_text", sa.Text(), nullable=False),
        sa.Column("chapter_summary", sa.Text(), nullable=False),
        sa.Column("actual_word_count", sa.Integer(), nullable=False),
        sa.Column("new_character_candidates_json", sa.Text(), nullable=False),
        sa.Column("new_setting_candidates_json", sa.Text(), nullable=False),
        sa.Column("state_change_candidates_json", sa.Text(), nullable=False),
        sa.Column("foreshadow_candidates_json", sa.Text(), nullable=False),
        sa.Column("facts_to_confirm_json", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("llm_call_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["plan_id"], ["chapter_plans.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["novel_projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chapter_drafts")
    # ### end Alembic commands ###
